### ISSUE TITLE
isArray

### ISSUE THREAD

**Issue by corelgott** [thenativeweb/assertthat#14]
Hi,

I was just looking into your code to see if I could extend your ``is`` object to check for the actual might be an Array. Since ``is`` is an object you create within ``assert.that`` there is no way to add custom comparisons. It might be worth the thought to move ``is`` outside of ``assert.that`` to gain prototype access to it. So one cloud do something like:
```
Is.prototype.Array = function(actual) {
    return function() { 
       return Object.prototype.toString.call(actual) === '[object Array]';
    }
}
```

Cheers,

Corelgott

**Comment by goloroden** [comment]
That's right … I think this is an idea that's worth thinking about, so thanks for bringing it up :-)

Just one question: Is the `Array` sample just an (arbitrary) sample because you needed one, or is this an actual need that you currently have?

(If the second, I could come up with a fix pretty fast).

**Comment by corelgott** [comment]
see my pull request

**Comment by goloroden** [comment]
Checking whether something is an array can be done using

```javascript
assert.that(...).is.ofType('array');
```

Hence, I'm going to close this issue.
