### ISSUE TITLE
confusing error if checking for error

### ISSUE THREAD

**Issue by stefanheine** [thenativeweb/assertthat#17]
```
   test('answers /favicon.ico', done => {
     request.get('http://localhost:9000/favicon.ico')
     .end((err, response) => {
       assert.that(err).is.equalTo('Error: Not Found');
       assert.that(response.statusCode).is.equalTo(404);
       done();
     });
   });
```

I'm aware (now) that this is not correctly coded and should be:

`      assert.that(err.message).is.equalTo('Not Found');`

but my original code leads to the test result:

>   1) authExample.js answers /favicon.ico:
>      Uncaught AssertionError: Expected 'Error: Not Found' to equal 'Error: Not Found'.

this is very confusing, as in fact the two strings shown are equal.

I would recommend that in such a case, when comparing an error object with a string, you should not simply display the stringified output, but somehow indicate that I actually compared with an object.

**Comment by goloroden** [comment]
I'm with you, that it *is* confusing at first sight, but IMHO this only happens once. When you once hit that problem, you know that it exists and how to solve it (which is a pretty easy task, and it should not happen too often).

On the other hand, it is very hard to change the behavior in a way that is consistent and only uses a reasonable amount of code. You have to think of lots of other cases. What if you use `not.equalTo` instead of `equalTo`? One should behave **exactly** like the other one, with a `!` in front of it. That's hard to get right and means lots of effort.

Also, you introduce a special case for a mixture of types. What about other options with mixed types? All this adds up very quickly and gets difficult to get right, for - as explained before - a very simple to solve problem that should not happen too often.

So, to cut a long story short: If you come up with a PR that handles *all* cases consistently and does not add lots of complexity to the code, I'm more than happy to merge it. But at least for now, I don't think that we will put any effort in this.
