### ISSUE TITLE
What about some breaking change documentation?

### ISSUE THREAD

**Issue by stheine** [thenativeweb/assertthat#35]
when you released 4.x, the initialization changed from `const assert = require('assertthat')` to `const assert = require('assertthat').default`.

what about some CHANGELOG or CHANGES or even a breaking changes section in the README?

**Comment by yeldiRium** [comment]
Hi!

Thank you for asking. We have unfortunately don't have a consensus on changelogs yet, but plan to add them in the future.
However, if you look in the "Quick Start" section in the [Readme.md](https://github.com/thenativeweb/assertthat/blob/master/README.md) you will find the following lines:

> First you need to add a reference to assertthat to your application.
> 
> ```javascript
> const assert = require('assertthat').default;
> ```
> 
> If you use TypeScript, use the following code instead:
> 
> ```typescript
> import assert from 'assertthat';
> ```

I hope that clears this up.

Kind regards,
yeldiR

**Comment by stheine** [comment]
Hi,

well, I actually figured it out, but it took took long. usually, when I see a major version change, I scan the npm documentation (README) for breaking changes (and rarely find them). then I switch over to github, looking for CHANGES or CHANGELOG (and this is where I typically find it). next, I went to the releases tab to find nothing documented there per release, so I went to the commits, finding that you made changes to typescript (not using typescript, I have no clue about the implications, so I just assumed that you just increased the major version to indicate the typescript support and that it actually wouldn't break).
so I updated. and failed.

then I started reading the README... and yes, there I found how to use it.

but it could have been so much easier... that's why I thought I'd leave this feedback.

**Comment by yeldiRium** [comment]
Thank you for your feedback.

We'll try to be more transparent with the changes we make. We don't document the GitHub releases so far, because we create them as git tags using roboter instead of creating them manually in the GUI. However, a changelog file (or at least a changelog section in the readme) is something we're considering.

I'll close this for now and will take the feedback into our next discussion.

**Comment by stheine** [comment]
@goloroden 
Hi Golo,

once more, a breaking change without any breaking change docs?! From last time, I had been warned, but I still don't like it.
I would really like you to publish some changelog/ breaking change docs in case of such changes.

Regards
  Stefan

**Comment by goloroden** [comment]
Hi @stheine 👋 

Once again, see the commit history: https://github.com/thenativeweb/assertthat/commits/master

If you skip all the dependabot commits, there are three commits between 4.x and 5.0, one of them named `Introduce top-level named export.`

I know that searching the commit history is not an optimal solution, but the commit messages tell what has changed (oh, and that it's a breaking change is obvious, since it's been a major release).

However, we are currently thinking about introducing `semantic-release`, which may solve this issue finally 😊 

(It's not that we don't want to solve this, please don't get this wrong, it's just that we want to solve this in a way that is reasonable, and works the same for all our repositories, without introducing additional problems.)

So stay tuned … 😊

**Comment by goloroden** [comment]
@stheine Great news 🎉 

See https://github.com/thenativeweb/assertthat/blob/master/CHANGELOG.md 😉
